## Gitlab CI/CD template for Moodle plugins By Ldesign Media.
## Author: Hamza Tamyachte
## Copyright 17/07/2024 Mfreak.nl | LdesignMedia.nl - Luuk Verhoeven

services:
  - mysql:latest
  - name: selenium/standalone-chrome:3
    alias: selenium-standalone-chrome
variables:
  PHP_VERSION: "8.0"
  TRAVIS_BUILD_DIR: "$CI_PROJECT_DIR"
  MOODLE_REPO: "$MOODLE_WORKPLACE_REPO"
  MOODLE_REPO_LMS: "https://github.com/moodle/moodle.git"
  # Moodle branches.
  # Workplace.
  MOODLE_BRANCH_WORKPLACE404S: WORKPLACE_404_3
  MOODLE_BRANCH_WORKPLACE403S: WORKPLACE_403_7
  MOODLE_BRANCH_WORKPLACE402S: WORKPLACE_402_10
  MOODLE_BRANCH_WORKPLACE401S: WORKPLACE_401_13
  # LMS.
  MOODLE_BRANCH_LMS404: MOODLE_404_STABLE
  MOODLE_BRANCH_LMS403: MOODLE_403_STABLE
  MOODLE_BRANCH_LMS402: MOODLE_402_STABLE
  MOODLE_BRANCH_LMS401: MOODLE_401_STABLE
  MOODLE_BRANCH_LMS400: MOODLE_400_STABLE
  MOODLE_BRANCH_LMS39: MOODLE_39_STABLE
  # Selenium.
  MOODLE_BEHAT_WDHOST: "http://selenium-standalone-chrome:4444/wd/hub"
  MOODLE_START_BEHAT_SERVERS: "NO"
  # Database.
  DB: "mysqli"
  MYSQL_ROOT_PASSWORD: "superrootpass"
  MYSQL_ALLOW_EMPTY_PASSWORD: "true"

.scriptshorttest: &scriptshorttest
  image: moodlehq/moodle-workplace-plugin-ci:$PHP_VERSION
  script:
    # Update packages and/or install.
    - apt update && apt install -y mariadb-client
    - cd $CI_PROJECT_DIR/..
    - echo $MOODLE_REPO
    - rm -rf moodle
    # Install Moodle includes the setup of PHPUnit and Behat when tests exist in the plugin directory.
    - export IPADDRESS=`grep "${HOSTNAME}$" /etc/hosts |awk '{print $1}'`
    - export MOODLE_BEHAT_WWWROOT="http://${IPADDRESS}:8000"
    - moodle-plugin-ci install --db-user=root --db-pass=superrootpass --db-host=mysql -vvv
    - cd moodle
    - php -S ${IPADDRESS}:8000 -t $CI_PROJECT_DIR/../moodle > /dev/null 2>&1 &
    - moodle-plugin-ci phplint
    - moodle-plugin-ci phpcpd
    - moodle-plugin-ci phpmd
    - moodle-plugin-ci codechecker
    - moodle-plugin-ci mustache || true
    - moodle-plugin-ci validate
    - moodle-plugin-ci savepoints
    - moodle-plugin-ci grunt || true
    - moodle-plugin-ci phpdoc
    - moodle-plugin-ci phpunit
    - moodle-plugin-ci behat --suite default --profile chrome
  except:
    - tags
